; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FROM INNO SETUP FOR DETAILS ON CREATING SCRIPT FILES.

#define OutputBaseFilename "OpenRailsTestingDVDSetup"

#include "..\OpenRails shared\OpenRails.iss"